from dotenv import load_dotenv
import os
import streamlit as st
from scripts.preprocess import preprocess_and_save
from rag_components.query_handler import generate_response, format_response
from rag_components.model_handling import LLM

# Load environment variables once
load_dotenv()

# Environment variables are now globally available
openai_api_key = os.getenv("OPENAI_API_KEY")
huggingface_token = os.getenv("HUGGINGFACE_HUB_TOKEN")

# Title and description
st.title("Question Answering with RAG and LLMs")
st.write("Enter your question below and receive an answer generated by the selected Language Model.")

# Sidebar for model selection
st.sidebar.title("Model Selection")
llm_options = {
    "OpenAI GPT-3.5 Turbo": LLM.GPT_35_TURBO,
    "OpenAI GPT-4o Mini": LLM.GPT_4O_MINI,
    "Google Gemma 7B": LLM.GEMMA_7B_IT,
    "Meta LLaMA 2 7B Chat": LLM.LLAMA_2_7B_CHAT,
    "Mistral 7B Instruct": LLM.MISTRAL_7B_INSTRUCT,
    "Local Llama-2 7B Server": LLM.LOCAL_LLM_SERVER,
    "Azure OpenAI Deployment": LLM.AZURE_OAI_DEPLOYMENT
}
selected_model_name = st.sidebar.selectbox("Choose an LLM:", list(llm_options.keys()))
selected_llm = llm_options[selected_model_name]

num_context_items = st.sidebar.slider("Number of Context Items", min_value=0, max_value=10, value=5)

# Add options in the sidebar
st.sidebar.title("Search Options")
use_lexical_search = st.sidebar.checkbox(
    "Use Lexical Search", 
    value=False,
    disabled=(num_context_items == 0)
)
use_reranking = st.sidebar.checkbox(
    "Use Reranking",
    value=False,
    disabled=(num_context_items == 0)
)

# Form for user input
with st.form(key="query_form"):
    # User input for query
    user_query = st.text_input("Your Question:", value="")
    
    # Submit button inside the form
    submit_button = st.form_submit_button(label="Get Answer")

# Check if form was submitted (via button or Enter key)
if submit_button:
    if user_query.strip() == "":
        st.warning("Please enter a question.")
    else:
        # Display a spinner while processing
        with st.spinner("Processing your query..."):
            # Call preprocessing function
            folder_path = "./data"
            patterns = ['See discussions, ', 'References', 'Subject Index', 'Weizenbaum, J.: Wer']
            embedding_file = "embeddings.index"
            bm25_file = "bm25.pkl"

            # Run preprocessing (if needed)
            index, bm25_model, tokenized_chunks, pages_and_chunks = preprocess_and_save(
                folder_path=folder_path, 
                patterns=patterns, 
                output_embedding_file=embedding_file, 
                output_bm25_file=bm25_file
            )

            # Generate response
            response = generate_response(
                llm=selected_llm, 
                query=user_query,
                pages_and_chunks=pages_and_chunks,
                tokenized_chunks=tokenized_chunks,
                index=index,
                bm25_model=bm25_model,
                num_context_items=num_context_items,
                use_lexical_search=use_lexical_search,
                use_reranking=use_reranking,
            )

        formatted_response = format_response(
            response, 
            return_answer_only=False
        ) 

        # Display the response
        st.subheader("Answer:")
        print(formatted_response)
        st.write(formatted_response['answer'])

        # Display context if available
        if num_context_items > 0 and 'context_source' in formatted_response and 'context_content' in formatted_response:
            st.subheader("Context:")
            # Loop through the context sources and contents and display them
            for i, (source, content) in enumerate(zip(formatted_response['context_source'], formatted_response['context_content']), start=1):
                st.write(f"**Source {i}:** {source}")
                st.write(f"**Text:** {content}")